[tools]
bun = "1.2.10"
flutter = "3.27.1"
dprint = "0.49.1"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './tools/bootstrap.sh'
alias = "bs"

[tasks.clean]
description = "Clean this workspace."
run = [
  'bun run clean',
  'melos clean',
]

[tasks.cspell]
description = "Run cspell to check spelling."
run = [
  'bun run cspell lint',
]
