name: template_workspace
environment:
  sdk: ^3.6.0

workspace:
  # apps
  - apps/app
  - apps/catalog
  - apps/website
  # cores
  - packages/cores/core
  - packages/cores/data
  - packages/cores/designsystem
  - packages/cores/model
  - packages/cores/ui
  # features
  - packages/features/debug_mode
  - packages/features/force_update
  - packages/features/maintain
  - packages/features/setting
  - packages/features/webview
  # samples
  - packages/samples/github_repository
  - samples/github_app

dev_dependencies:
  mason_cli: ^0.1.0-dev.55
  melos: ^6.3.0
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dependency_overrides:
  file: ^7.0.0
  path: ^1.9.1
