name: "Cleanup Samples"
description: "Deletes statements related to samples."

inputs:
  pubspec-yaml-path:
    description: "Path to the pubspec.yaml file"
    default: "pubspec.yaml"
  vscode-launch-json-path:
    description: "Path to the launch.yaml file"
    default: ".vscode/launch.json"

runs:
  using: "composite"
  steps:
    - name: Remove samples from pubspec.yaml
      run: |
        PUBSPEC_PATH="${{ inputs.pubspec-yaml-path || 'pubspec.yaml' }}" # 入力でパスを指定可能にする (デフォルトは pubspec.yaml)

        # yq を使ってサンプルパッケージのパスを削除し、一時ファイルに出力
        # test 関数で正規表現に一致するものを選択
        yq eval 'del(.workspace[] | select(test("^(packages/samples/|samples/).*")))' "$PUBSPEC_PATH" > "$PUBSPEC_PATH.new"

        # 元のファイルと変更後の一時ファイルの差分を取得 (空行や空白の差を無視)
        # 差分がなくてもエラーにしないように || true をつける
        diff -U0 -w -b --ignore-blank-lines "$PUBSPEC_PATH" "$PUBSPEC_PATH.new" > "$PUBSPEC_PATH.diff" || true

        # 差分を元のファイルに適用
        patch "$PUBSPEC_PATH" < "$PUBSPEC_PATH.diff"

        # 一時ファイルを削除
        rm "$PUBSPEC_PATH.new" "$PUBSPEC_PATH.diff"
      shell: bash

    - name: Strip comments from launch.json
      run: strip-json-comments ${{ inputs.vscode-launch-json-path }} > ${{ inputs.vscode-launch-json-path }}.temp
      shell: sh

    - name: Remove samples configurations from launch.json
      run: >
        jq -n -f ${{ inputs.vscode-launch-json-path }}.temp |
        jq '
        .configurations |= map(select(.cwd | strings | startswith("samples/") | not))
        '
        > ${{ inputs.vscode-launch-json-path }}
      shell: sh

    - name: Remove temp file
      run: rm ${{ inputs.vscode-launch-json-path }}.temp
      shell: sh
