name: cores_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  cores_designsystem:
    path: ../designsystem
  cores_model:
    path: ../model
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
