include: package:yumemi_lints/flutter/3.24/recommended.yaml

analyzer:
  plugins:
    # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # https://pub.dev/packages/freezed#install
    invalid_annotation_target: ignore
