name: design_theme
description: A starting point for Dart libraries or applications.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  test: ^1.25.8
