name: features_force_update
description: "This package provides forced update feature."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  cores_core:
    path: ../../cores/core
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yumemi_lints: ^2.2.0
