name: catalog
description: "A UI catalog application."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  cores_designsystem:
    path: ../../packages/cores/designsystem
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.11
  widgetbook_generator: ^3.7.0
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
