name: features_setting
description: "This package provides setting feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.8.0
  riverpod_generator: ^2.4.0
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
