name: Check package dependencies
description: Report package updates and differences in notation in pr comments.

inputs:
  base_branch:
    description: 'PR base branch'
    required: true
  pr_number:
    description: 'PR Number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check package dependencies
      id: dependencies
      run: |
        diff=$(dart run ./tools/diff_yaml.dart ${{ inputs.base_branch }} pubspec.yaml pubspec.lock)

        if [ -z "$diff" ]; then
          echo "No change in pubspeck.lock"
        else
          echo "There is a change in pubspeck.lock."

          path="$GITHUB_WORKSPACE/$(date +%Y%m%d%H%M%S)"
          echo "$diff" > $path
          echo "path=$path" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ inputs.gh_token }} 
      shell: bash

      # https://github.com/peter-evans/create-or-update-comment
    - name: Comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      with:
        issue-number: ${{ inputs.pr_number }} 
        body-path: ${{ steps.dependencies.outputs.path }}
