name: github_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  samples_github_repository:
    path: ../../packages/samples/github_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
