name: webview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.2.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  yumemi_lints: ^4.0.0

flutter:
  uses-material-design: true
