name: Debug

# TODO: マージ前に消す

on:
  push:
    branches:
      - docs-website

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Fetch sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Remove unnecessary files
        uses: ./.github/actions/remove-unnecessary-files

      - name: Debug
        run: |
          git diff
