name: Deploy to GitHub Pages on PR

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".idea/**"
      - ".vscode/**"
      - "apps/app/**"
      - "docs/**"
      - "scripts/**"
      - "tools/**"
      - "mason.yaml"
      - "**/docs/**"
      - "**/test/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_DIR: apps/catalog
  DEPLOY_DIR: ${{ github.event.number }}

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    # NOTE: See https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/GITHUB_PAGES_PREVIEW.md
    if: ${{ github.repository_owner == 'yumemi-inc' && github.event.repository.name == 'flutter-mobile-project-template' }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Create deploy directory
        run: mkdir -p ${{ env.PROJECT_DIR }}/${{ env.DEPLOY_DIR }}

      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/${{ env.DEPLOY_DIR }}/ --output ${{ env.PROJECT_DIR }}/deploy
        working-directory: ${{ env.PROJECT_DIR }}

      # https://github.com/actions/upload-pages-artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ${{ env.PROJECT_DIR }}/${{ env.DEPLOY_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ env.DEPLOY_DIR }}
    permissions:
      pages: write
      id-token: write
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
