name: Deploy to GitHub Pages on PR

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".idea/**"
      - ".vscode/**"
      - "apps/app/**"
      - "docs/**"
      - "scripts/**"
      - "tools/**"
      - "mason.yaml"
      - "**/docs/**"
      - "**/test/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_DIR: apps/catalog
  DEPLOY_DIR: ${{ github.event.number }}

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    # NOTE: See https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/GITHUB_PAGES_PREVIEW.md
    if: ${{ github.repository_owner == 'yumemi-inc' && github.event.repository.name == 'flutter-mobile-project-template' }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/${{ env.DEPLOY_DIR }}/
        working-directory: ${{ env.PROJECT_DIR }}


      - name: Create combined deployment directory
        run: mkdir -p deployment-output/${{ env.DEPLOY_DIR }}

      - name: Copy build to deployment directory
        run: cp -R ${{ env.PROJECT_DIR }}/build/web/. deployment-output/${{ env.DEPLOY_DIR }}

      # --- Handle SPA Routing with 404.html (Crucial for direct access to sub-paths) ---
      # This creates a 'root' 404.html to catch any direct access that isn't a valid path.
      # It should point to a central index.html or a custom 404 page if you have one.
      # For multiple apps, you might need a custom 404.html that directs users to your main landing page.
      # If 'fuga' and 'saga' are truly independent, you might also need 404.html inside their respective deployment folders
      # for internal routing (e.g., deployment-output/hoge/fuga/404.html).
      - name: Create a basic root index and 404 for navigation (Optional but recommended)
        run: |
          echo '<!DOCTYPE html><html><head><title>My Apps</title></head><body><h1>Welcome!</h1><p>Visit <a href="./${{ env.DEPLOY_DIR }}/">Fuga App</a> or <a href="./hoge/saga/">Saga App</a></p></body></html>' > deployment-output/index.html
          cp deployment-output/index.html deployment-output/404.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This is the directory that will be the root of your GitHub Pages site.
          # Its internal structure will define your URL paths.
          path: ./deployment-output

      # https://github.com/actions/configure-pages
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b

      # https://github.com/actions/upload-pages-artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ${{ env.PROJECT_DIR }}/${{ env.DEPLOY_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ env.PROJECT_DIR }}/${{ env.DEPLOY_DIR }}
    permissions:
      pages: write
      id-token: write
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
