name: pubspec.lock diff

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/pubspec.lock'

  # TODO: 検証用のため、検証完了次第削除する
  # push:
  #   branches:
  #     - feature/GH-377
  workflow_dispatch: {}

jobs:
  pubspec-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Check diff of pubspec.lock
        run: |
          diff=$(dart run ./tools/diff_yaml.dart pubspec.lock)

          if [ -z "$diff" ]; then
            echo "No change in pubspeck.lock"
          else
            echo "There is a change in pubspeck.lock."
            gh pr comment "${{ github.event.number }}" --body "$diff"
          fi
